// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Palet dari DESIGN.md (Monochrome Gallery)
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1b1b1b',
        'on-surface-variant': '#4c4546',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f1f1f1',
        outline: '#7e7576',
        'outline-variant': '#cfc4c5',
        'surface-tint': '#5e5e5e',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1b',
        'on-primary-container': '#848484',
        'inverse-primary': '#c6c6c6',
        secondary: '#5d5f5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#dfe0e0',
        'on-secondary-container': '#616363',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1b1c1c',
        'on-tertiary-container': '#858383',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c6',
        'on-primary-fixed': '#1b1b1b',
        'on-primary-fixed-variant': '#474747',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#454747',
        'tertiary-fixed': '#e4e2e1',
        'tertiary-fixed-dim': '#c8c6c6',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474747',
        background: '#f9f9f9',
        'on-background': '#1b1b1b',
        'surface-variant': '#e2e2e2',
      },
      fontFamily: {
        'display': ['var(--font-playfair)', 'serif'],
        'sans': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl-mobile': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      spacing: {
        'container-max': '1440px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'stack-xl': '160px',
        'stack-lg': '80px',
        'stack-md': '40px',
        'gutter': '24px',
      },
      borderRadius: {
        DEFAULT: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '9999px',
      },
      borderWidth: {
        DEFAULT: '1px',
        0: '0',
        2: '2px',
        3: '3px',
        4: '4px',
      },
    },
  },
  plugins: [],
}